React carousel component
AndyPark20/c1120-code-solutions pull request #129
Opened 2021-01-22 15:35 UTC by AndyPark20

![React-CAROUSEL](https://user-images.githubusercontent.com/69870979/105511051-523b7980-5c84-11eb-959f-3d89bed2e265.gif)

2021-01-25 23:24 UTC, scbowler requested changes
Great job getting it to work! Here is some feedback to help improve it and handle things in a more "react" way. Let me know if you have any questions on the requested changes!

2021-01-25 23:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    }, 3000)
This is not a good place to do this. It would be better to start this in `componentDidMount`

2021-01-25 23:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    }
Instead of using class names and ids to determine what has been clicked you should make 3 separate click handlers, for example: `goToPreviousImage`, `goToNextImage`, `dotClicked` then put the appropriate click handler directly on the element that will trigger it

2021-01-25 23:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    return circle;
You can not have a separate array of ids passed in as props, there is too much room for error with that approach, you should use the info you already have, IE the array of images

2021-01-25 23:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    return (<img src={picture} alt="pokemon" />)
If the JSX is on the same line as the `return` statement, you don't need the parentheses

2021-01-25 23:24 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    this.state = ({ counter: 0 })
You don't need the parentheses here

2021-01-26 00:36 UTC, AndyPark20 commented on react-carousel-component/src/carousel.jsx
> +    return (<img src={picture} alt="pokemon" />)
noted!

2021-01-26 00:36 UTC, AndyPark20 commented on react-carousel-component/src/carousel.jsx
> +    this.state = ({ counter: 0 })
Noted as well!

2021-01-26 01:33 UTC, scbowler requested changes
Looking better! Couple more changes, not as much as last time, I promise!

2021-01-26 01:33 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    if (iconClick === iconClick) {
This will always be `true` you are checking if something is equal to itself

2021-01-26 01:33 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +  }
Are you still using this method somewhere?

2021-01-26 01:33 UTC, scbowler commented on react-carousel-component/src/carousel.jsx
> +    this.circleChange = this.circleChange.bind(this)
Since `circleChange` is called directly in the `render` method, you don't need to bind it here

2021-01-26 01:33 UTC, scbowler commented on react-carousel-component/dist/style.css
> +.fa-chevron-right, .fa-chevron-left{
I missed this last time. You don't want to directly target class names from 3rd party css libraries in your CSS. This changes the expected behavior of those classes and may cause confusion and issues with other developers working on the project, or even with yourself down the road. A better solution would be to make a utility class called something like: `font-size-3x`. In this project this isn't much of a concern of course but it is a bad habit to get into.

2021-01-26 01:38 UTC, AndyPark20 commented on react-carousel-component/src/carousel.jsx
> +  }
Sorry Scott! I totally forgot to delete this method...

2021-01-26 01:46 UTC, AndyPark20 commented on react-carousel-component/src/carousel.jsx
> +    this.circleChange = this.circleChange.bind(this)
Noted! Also i have removed it as a value for onClick attribute on line 71

2021-01-26 01:50 UTC, AndyPark20 commented on react-carousel-component/dist/style.css
> +.fa-chevron-right, .fa-chevron-left{
Ah thanks again for the hint on this!

2021-01-26 18:49 UTC, scbowler requested changes
Looking real good! One final change!

2021-01-26 18:49 UTC, scbowler commented on react-carousel-component/src/index.jsx
> +ReactDOM.render(<Carousel pokemon={['./001.png','./004.png','./007.png','./025.png','./039.png']} dotId={dotId} />,document.querySelector('#root'))
Since you are no longer using the `dotId` array delete it and the prop for it on `<Carousel/>`

2021-01-27 22:57 UTC, scbowler approved these changes
Awesome job on the refactors! Looking good! 👍

2021-01-28 20:38 UTC, merged