completed api-authorization
AndyPark20/c1120-code-solutions pull request #139
Opened 2021-01-26 23:44 UTC by AndyPark20

![image](https://user-images.githubusercontent.com/69870979/105921122-53a2d400-5fed-11eb-95b4-0c9a1e1faaea.png)

2021-01-26 23:50 UTC, Zhiwutian requested changes
tiny update!

2021-01-26 23:50 UTC, Zhiwutian commented on api-authorization/server/authorization-middleware.js
> +  if(!req.headers){
you don't want to do a blanket check for headers, you want to try to access the token first and then check if there is a token good sir! If there is no token you want to send the Error

2021-01-26 23:51 UTC, AndyPark20 commented on api-authorization/server/authorization-middleware.js
> +  if(!req.headers){
Ah well noted Brett!

2021-01-27 00:12 UTC, Zhiwutian approved these changes
👍

2021-01-27 00:13 UTC, merged